### ISSUE TITLE
[Beginner][Translate] V2.3.0 Feature pg_unlock Document

### ISSUE THREAD

**Issue by bartdong** [OpenTenBase/OpenTenBase#41]
https://github.com/OpenTenBase/docs/blob/main/docs/guide/11-pg_unlock.md
Needs to be translated into English and saved as 11-pg_unlock.en.md

**Comment by Amber-niubi** [comment]
Done.[https://github.com/OpenTenBase/docs/pull/4](https://github.com/OpenTenBase/docs/pull/4)
