### ISSUE TITLE
 command not found

### ISSUE THREAD

**Issue by QlQlqiqi** [OpenTenBase/OpenTenBase#55]
### Question (问题)
Following this [tutorial](https://docs.opentenbase.org/guide/01-quickstart/), I have compiled source code, finished configure-file, such as: `ssh`, `.bashrc`, `.pgxc_ctl.conf`.  In `/usr/bin/bash`, I can run command like `pg_ctl`. But running `init all` command through `pgxc_ctl` tool can cause: `bash: line 1: pg_ctl: command not found`.

我已经根据 [官方指导](https://docs.opentenbase.org/guide/01-quickstart/) 编译源码，配置好了 `.ssh`、`.bashrc`、`.pgxc_ctl.conf` 等配置文件，在 `/usr/bin/bash` 中手动输入 `pg_ctl ` 等命令成功，但是通过 `pgxc_ctl` 工具运行 `init all`，会显示：`bash: line 1: pg_ctl: command not found`。

### screenshot (截图)
![1708413056916](https://github.com/OpenTenBase/OpenTenBase/assets/65795838/5c92d812-eb42-46dc-9ea8-d757c2374112)

### goal (求助)
how to deal with it, thx.
请问如何解决

**Comment by QlQlqiqi** [comment]
I can supplement it if something lack.
如果缺少什么信息的话，我及时补充。

**Comment by bartdong** [comment]
if you use Ubuntu and see `initgtm: command not found` while doing "init all", you may add `${INSTALL_PATH}/opentenbase_bin_v2.0/bin` to `/etc/environment` and try again

**Comment by QlQlqiqi** [comment]
everything is right. 

thx very much.
